### ISSUE TITLE
Feature request: highlight whole line

### ISSUE THREAD

**Issue by yscialom** [johnkerl/lumin#2]
### Summary
Add an option to highlight entire lines where a match is found.

### Example (using `**highlighted**` to denote colour):
```
# Default behaviour                          # Requested behaviour
ps | lumin zsh                               ps | lumin -f zsh
   PID TTY          TIME CMD                    PID TTY          TIME CMD                 
 245430 pts/3    00:00:04 **zsh**            ** 245430 pts/3    00:00:04 zsh**
 245435 pts/3    00:00:00 **zsh**            ** 245435 pts/3    00:00:00 zsh**   
 245494 pts/3    00:00:00 **zsh**            ** 245494 pts/3    00:00:00 zsh**
 245496 pts/3    00:00:00 **zsh**            ** 245496 pts/3    00:00:00 zsh**
 245497 pts/3    00:00:00 gitstatusd-linu     245497 pts/3    00:00:00 gitstatusd-linu
 253241 pts/3    00:00:00 ps                  253241 pts/3    00:00:00 ps
 253242 pts/3    00:00:00 lumin               253242 pts/3    00:00:00 lumin
```

### Full Request
Add a command-line option `-f`/`--full-lines` to make lumin highlight not only the found matches but the entire lines containing at least one match.

### Motivation
I'm using a lot of `lumin ".*pattern.*"` when searching for technical information in logs where I need the context. For instance, this is a common line I find in my shell history:
```smartctl -A /dev/sdc | lumin "^190.*"```
It let me check a S.M.A.R.T. report entirely but with a highligh on attribut ID #90.

**Comment by johnkerl** [comment]
Awesome idea @yscialom ! :)

**Comment by yscialom** [comment]
Thanks a lot @johnkerl! 

Any plan to do a release so I can enjoy this feature?
